platform :ios, '9.0'

target 'GelecekBilimde' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GelecekBilimde
    pod 'Firebase/Analytics'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'GoogleSignIn'
    pod 'RealmSwift'
    
  target 'GelecekBilimdeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GelecekBilimdeUITests' do
    # Pods for testing
  end

end
